{
    flake.modules.nixos.server =
        # Do not modify this file!  It was generated by ‘nixos-generate-config’
        # and may be overwritten by future invocations.  Please make changes
        # to /etc/nixos/configuration.nix instead.
        {
            config,
            lib,
            pkgs,
            modulesPath,
            ...
        }: {
            imports = [
                (modulesPath + "/installer/scan/not-detected.nix")
            ];

            boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
            boot.initrd.kernelModules = [];
            boot.kernelModules = ["kvm-intel"];
            boot.extraModulePackages = [];
            swapDevices = [
                {
                    device = "/swap/swapfile";
                    size = 20480; # 20GB in MB
                }
            ];

            fileSystems."/" = {
                device = "/dev/disk/by-uuid/41f16f18-9e9a-4e96-8b1f-7ab5c65f878c";
                fsType = "btrfs";
                options = ["subvol=root"];
            };

            fileSystems."/home" = {
                device = "/dev/disk/by-uuid/41f16f18-9e9a-4e96-8b1f-7ab5c65f878c";
                fsType = "btrfs";
                options = ["subvol=home"];
            };

            fileSystems."/nix" = {
                device = "/dev/disk/by-uuid/41f16f18-9e9a-4e96-8b1f-7ab5c65f878c";
                fsType = "btrfs";
                options = ["subvol=nix"];
            };

            fileSystems."/var/log" = {
                device = "/dev/disk/by-uuid/41f16f18-9e9a-4e96-8b1f-7ab5c65f878c";
                fsType = "btrfs";
                options = ["subvol=log"];
            };

            fileSystems."/swap" = {
                device = "/dev/disk/by-uuid/41f16f18-9e9a-4e96-8b1f-7ab5c65f878c";
                fsType = "btrfs";
                options = ["subvol=swap" "noatime"];
            };

            fileSystems."/boot" = {
                device = "/dev/disk/by-uuid/E107-9DBE";
                fsType = "vfat";
                options = ["fmask=0022" "dmask=0022"];
            };

            nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
            hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
        };
}
