{
    flake.modules.nixos.base = {pkgs, ...}: {
        services.envfs.enable = true;
        programs.nix-ld.enable = true;
        programs.nix-ld.libraries = with pkgs; [
            qt6.qtdeclarative
            qt6.qtbase
            alsa-lib
            at-spi2-atk
            at-spi2-core
            atk
            cairo
            cups
            curl
            dbus
            expat
            fontconfig
            freetype
            fuse3
            gdk-pixbuf
            glib
            gtk3
            icu
            libGL
            libappindicator-gtk3
            libdrm
            libglvnd
            libnotify
            libpulseaudio
            libunwind
            libusb1
            libuuid
            libxkbcommon
            mesa
            nspr
            nss
            openssl
            pango
            pipewire
            stdenv.cc.cc
            systemd
            vulkan-loader
            libx11
            libxscrnsaver
            libxcomposite
            libxcursor
            libxdamage
            libxext
            libxfixes
            libxi
            libxrandr
            libxrender
            libxtst
            libxcb
            libxkbfile
            libxshmfence
            zlib
        ];
    };
}
